### ISSUE TITLE
Migration NR to Device Agent

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/nr-tools-plugin#14]
## Description
This epic aims to provide an effortless migration path for Node-RED users to the FlowForge Device Agent by introducing a user interface (UI) for creating and configuring the required device.yml file. The proposed solution will improve the user experience and allow quick onboarding of devices.

## Story
As a Node-RED user, I want an effortless migration from Node-RED to the Device Agent. This will ensure a smooth user experience and enable users to quickly onboard their devices.

## Background
Currently, the FlowForge Device Agent requires a device.yml file to run a Node-RED instance. As a result, it is challenging to preinstall the device agent on 3rd party devices because shell access for device.yml creation and configuration is necessary.

## Goals

- [ ] Detect the absence and presence of a device.yml config file
- [ ] Allow the user to create a device.yml file via UI
- [ ] Implement a switch option to the device agent

### Original Issue
https://github.com/flowforge/flowforge-device-agent/issues/75

**Comment by joepavitt** [comment]
Not a path we'll be going down now, closing
